### ISSUE TITLE
Controller implementation?

### ISSUE THREAD

**Issue by IcerOut** [IcerOut/UniversalUnitConverter#1]
Do we want the controllers implemented as a class with a convert() method or as a single function?

Both seem equally valid to me

**Comment by JulyArk** [comment]
For standardization sake I think the class option is better. I also think both are valid and side more on preference than anything.

**Comment by IcerOut** [comment]
Sounds good. So we'll have a class with the name "Controller{UnitType}" and a single method "convert()"

**Comment by JulyArk** [comment]
Great! It's also good because if the unexpected happens other functions can be simply added without changing any existing code.
